### ISSUE TITLE
Incorporate cluster?

### ISSUE THREAD

**Issue by Athanasiamo** [muschellij2/fslr#13]
Hi. Love this package, it's been really nice to grab data straight into R for further use.

Would you consider making a wrapper for `cluster` too? Would be beneficial for tables etc.

Just a suggestion, keep up the good work!

**Comment by muschellij2** [comment]
I haven't been able to test it out very much yet, but https://github.com/muschellij2/fslr/commit/832e3b7999f896b92838ece9c03a6453db18f98c should have incorporated this.

```r
devtools::install_github("muschellij2/fslr")
```

I have an example in there, using an image as one to be thresholded, which may be inappropriate, but it should work as long as `FSL` and `fslr` installed:
```r
library(fslr)
if (have_fsl()) {
file = mni_fname(brain = TRUE, mask = FALSE)
threshold = 6000
clus = fsl_cluster(file, threshold)
}
```

Let me know if this works for you and I'd love some input for some examples with this!

**Comment by muschellij2** [comment]
As this example "works", I'm closing.

**Comment by Athanasiamo** [comment]
No need to re-open the ticket. I didnt get notified of this before, so sorry for not followin up. I have workshops all week, but I'll look at this over the weekend/next week, and let you know how I get on using it :)
