### ISSUE TITLE
Problems about FSLr installation with FSL6.0 on Ubuntu 18.04 LST

### ISSUE THREAD

**Issue by Jackie-Zhu17** [muschellij2/fslr#17]
Hi all,

 I have struggled with these problems several days.Hope you can help me.
When I use the function `fsl_biascorrect`,it failed and says:
```
fast    -B --nopve --out="/tmp/Rtmpq11Eub/file2cc6356910d4" "/tmp/Rtmpq11Eub/file2cc679823327.nii.gz";

fast: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory
cannot remove file '/tmp/Rtmpq11Eub/file2cc6356910d4_seg.nii.gz', reason 'No such file or directory'cannot rename file '/tmp/Rtmpq11Eub/file2cc6356910d4_restore.nii.gz' to '/tmp/Rtmpq11Eub/file2cc6356910d4.nii.gz', reason 'No such file or directory'Error in oro.nifti::readNIfTI(..., reorient = reorient) : 
  File(s) not found!
```
So I googled a lot and come here,BUT there is something different between my situation and `#issue10` posted on home page:
1.There is no folder called `fsl` under `\user\lib` in my enviroment.I just followed the instruction of the official website when I install FSL .
2. It seems that I didn't install FSL correctky.From the link:https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation/Linux,I passed the first check installation `echo $FSLDIR` and returns `/usr/local/fsl`,BUT it failed on the second check `flirt -version`,it returns `flirt: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory
` .HOWEVER,I can still open the GUI of FSL .I don't know what I am supposed to do.

**Comment by Jackie-Zhu17** [comment]
I fixed this problem!!!Anyone who come across similar problems should do `sudo apt-get install libopenblas-base` in the terminal. After that,when you type `flirt -version`,it will return `FLIRT version 6.0`.And the function `fsl_biascorrect` will run correctly.This instruction is not included on the installation page of FSL for Linux.Hope more people can see that.

**Comment by muschellij2** [comment]
Yes - see: https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=fsl;d042c80e.1810
