### ISSUE TITLE
Cannot access when fsl is not installed into default path

### ISSUE THREAD

**Issue by chewnglow** [muschellij2/fslr#22]
Hi! The arch AUR installed the fsl into /opt/fsl which is differ from the default /usr/local/fsl and fsl cannot be automatically accessed. After adding `. ${FSLDIR}/etc/fslconf/fsl.sh`
 into `.Renviron`, it shows `$FSLOUTPUTTYPE` not setted. My zsh shell can run fsl normally. Thanks!

**Comment by muschellij2** [comment]
Please see `?get.fsl()` documentation:
> Finds the FSLDIR from system environment or getOption("fsl.path") for location of FSL functions

You can use `options(fsl.path = "/opt/fsl")` and retry.  `fslr` does not really support non-standard installations of FSL otherwise if that doesn't work.
