### ISSUE TITLE
Question about skull thickness measurement using FSL

### ISSUE THREAD

**Issue by xuesongle** [muschellij2/fslr#23]
@muschellij2 , I am taking a brain imaging research project for my university. One of the early steps requires measuring the thickness of skull from MRI image. 

As guided by the BET manual, "A    This runs both bet2 and betsurf programs in order to get the additional skull and scalp surfaces created by betsurf."

Given T1 weighted file 'sub-01_T1w.nii.gz' as an input, 'bet sub-01_T1w.nii.gz sub-01_T1w.nii_bet.nii.gz -R -m -A' command generates
following files:

sub-01_T1w_bet_outskull_mesh.nii.gz
sub-01_T1w_bet_inskull_mask.nii.gz   sub-01_T1w_bet_skull_mask.nii.gz
sub-01_T1w_bet_inskull_mesh.nii.gz   sub-01_T1w.nii_bet_inskull_mesh.vtk
sub-01_T1w_bet_mask.nii.gz           sub-01_T1w.nii_bet_mesh.vtk
sub-01_T1w_bet.nii.gz                sub-01_T1w.nii_bet_outskin_mesh.vtk
sub-01_T1w_bet_outskin_mask.nii.gz   sub-01_T1w.nii_bet_outskull_mesh.vtk
sub-01_T1w_bet_outskin_mesh.nii.gz   sub-01_T1w.nii.gz
sub-01_T1w_bet_outskull_mask.nii.gz

But I am not sure how to measure the thickness of skull by using those files. Would you be able to shed some light on this?  I know it is not discussion forum for FSL but wish you could provide some useful suggestions here. Many Thanks.

My initial understanding is to compute the distance between the 2 surface files, sub-01_T1w.nii_bet_inskull_mesh.vtk, and sub-01_T1w.nii_bet_outskull_mesh.vtk but could not figure it out which functions should I use in FSLR.

**Comment by nicholst** [comment]
@xuesongle this sounds like a very FSL specific question, independent of fslr; I’d try the FSL email list.

**Comment by xuesongle** [comment]
@nicholst Thanks, I post the question on FSL now.
