### ISSUE TITLE
problem with probtrackx

### ISSUE THREAD

**Issue by snaillyd** [muschellij2/fslr#25]
Hi John,
I want to use probtrackx. However, rstudio suggests that could not find function "probtrackx". Other functions in fslr work well. I can also run probtrackx in ubuntu.
![捕获](https://user-images.githubusercontent.com/28690261/70022869-a727b680-15d0-11ea-90e8-f1cf0f365f98.JPG)
Can you help me solve this problem? Thanks
Li

**Comment by muschellij2** [comment]
I have not ported that function and don't currently have time to do that.  If you'd like that through `fslr`, please submit a pull request with your changes.

**Comment by muschellij2** [comment]
Please see if this is fixed via https://github.com/muschellij2/fslr/commit/d84c24648974bc21481822b037a0d1f66e85edd3, by running 

```r
remotes::install_github("muschellij2/fslr")
``` 
and trying again.
