### ISSUE TITLE
Fsleyes - multiple files

### ISSUE THREAD

**Issue by mwaqar99** [muschellij2/fslr#26]
Is there a good way to load multiple NIFTI files that are already stored in environment variables into the fsleyes plugin (within R)?

A rather cumbersome solution I am using at the moment is to run a different fsl function and copy paths of individual files into the opts = "" part of the code. 
This does not work if I use the tempdir path...so I am assuming it requires NIFTI inputs.

**Comment by muschellij2** [comment]
You may want to look at https://github.com/muschellij2/papayaWidget.  

This also works:
```r
library(fslr)
files = file.path(fsl_std_dir(), c("MNI152_T1_2mm_brain.nii.gz", "MNI152_T1_2mm.nii.gz"))
fsleyes(files)
```
If you have a bunch of nifti objects, then do `list(image1, image2)` and pass that to `fslr::fsleyes`
