### ISSUE TITLE
Share library error even after the export its path. 

### ISSUE THREAD

**Issue by sj-choi** [muschellij2/fslr#34]
fslr experts and devlopers: 

I encountered an error when I ran an R code on Rstudio on Xubuntu 18.04 LTS VirtualBox on Windows 10 host. 

There was no issue with the Installation of {fslr} and {ATNsR}. I installed fsl v.5 using Neurodebian. 

As you suggested I included the "export LD_LIBRARY_PATH=/usr/lib/fsl/5.0:$LD_LIBRARY_PATH" in my .profile file on my linux VM. This did not clear the error and it remains.  

> DSC.Coef = try(fsl_dice(img_1,img_2))
fslmaths: error while loading shared libraries: libnewimage.so: cannot open shared object file: No such file or directory
fslmaths: error while loading shared libraries: libnewimage.so: cannot open shared object file: No such file or directory
fslstats: error while loading shared libraries: libnewimage.so: cannot open shared object file: No such file or directory
Error in system(cmd, intern = TRUE) : error in running command
In addition: Warning messages:
1: In system(cmd, intern = intern) : error in running command
2: In system(cmd, intern = intern) : error in running command

If you have any remedy or suggestions for this error, it would be greatly appreciated. 

Thank you.
SC

**Comment by muschellij2** [comment]
Can you take a look at https://github.com/muschellij2/fslr/issues/8 - currently I don't think we support Neurodebian out of the box, but rather an FSL install.
