### ISSUE TITLE
fslreorient2std <input_image> [output_image] 

### ISSUE THREAD

**Issue by yinkaiming1987** [muschellij2/fslr#5]
Dear John,

Could function fslreorient2std() has both the input_image and output_image? It seems now fslreorient2std() only accept one file as the input.

> fslreorient2std.help()
Usage: fslreorient2std <input_image> [output_image] fslreorient2std is a tool for reorienting the image to match theapproximate orientation of the standard template images (MNI152).It only applies 0, 90, 180 or 270 degree rotations.It is not a registration tool.It requires NIfTI images with valid orientation informationin them (seen by valid labels in FSLView).  This toolassumes the labels are correct - if not, fix that before using this.If the output name is not specified the equivalent transformation matrix is written to the standard output 

> fslreorient2std()
Error in checkimg(file, ...) : 
  argument "file" is missing, with no default

Thanks,
Kaiming

**Comment by muschellij2** [comment]
This request does not make sense with FSL syntax.  `fslreorient2std` takes in an input file and `outfile` argument.  Therefore, in fslr, there is an input and output.  In FSL, it changes the file in place.

**Comment by yinkaiming1987** [comment]
Dear John,

So I just need to run:

Image2 <- fslreorient2std(file = image1)

And the changes will be kept in Image2 here, am I right?

Thanks,
Kaiming

**Comment by muschellij2** [comment]
Correct.
