### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by aljensen89** [muschellij2/fslr#7]
I am working on a Mac with R version 3.2.1 (not through a virtual machine, directly with the Mac) and am trying to install fslr.  I have entered the following commands:

if(!require(devtools)){install.packages('devtools')}
devtools::install_github("muschellij2/fslr")

and received the following output related to the second command:

Downloading GitHub repo muschellij2/fslr@master
from URL https://api.github.com/repos/muschellij2/fslr/zipball/master
Installing fslr
trying URL 'http://cran.cnr.berkeley.edu/bin/macosx/contrib/3.2/matrixStats_0.50.2'
Content type 'application/x-gzip' length 846649 bytes (826 KB)
'=================================================='
Error: Don't know how to decompress files with extension 50.2

When I looked into the error, it appears that something is chopping off the end of the filename through the CRAN mirror (the filename should be matrixStats_0.50.2.tgz).  Any help on why this is occurring?

**Comment by muschellij2** [comment]
Can you try another mirror for matrixStats? (https://cran.r-project.org/mirrors.html).

Also - have you tried to install by downloading the tarball (https://cran.r-project.org/web/packages/matrixStats/index.html)?
